# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Chae, Myoung-Ki
title: Student
email: ksi06356s@gmail.com
# email_title: Email (Email title override)
phone: 010-4580-1247
# phone_title: Phone (Phone title override)
website: github.com/cmk20182990
# website_title: Web (Website title override)
Kakaotalk: ksi06356s

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: cmk20182990
facebook_username: ksi06356s
instagram_username: dding.____
pinterest_username: ksi06356s
youtube_username: ksi06356s

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/'https://mail.google.com/mail/u/0?ui=2&ik=1554fe6b3d&attid=0.1&permmsgid=msg-a:r-7927289586287802584&th=183840115c08a96a&view=att&disp=safe&realattid=f_l8ll517b0'
about_content: | # this will include new lines to allow paragraphs

  What I'm interested in nowadays
    - Collecting world's liquor
    - Decorating my place
    - Watching V-Logs
    - Find unfamous place of Hallym University

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: AppleMango
        sub_title: part time-job(building chargers for  electric cars)
        caption: Date Range (September 2020 - Febuary 2021, June 2022 - August 2022)
        link: Link to company applemango.co.kr
        quote: >
          AppleMango is a electric car's charger building company, now LG has absorbed it. 
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Hallym University
        sub_title: Business Management / Big Data
        caption: Date Range (eg. 2018 - present, graduate will be February ,2024)
        quote: >
          Certificate for Global Innovation Strategy at Business College
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me ( My Goal )
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Before I graduate**
      I want to figure out what I want to do within this year. And I want to experience as many as I could take. 

      **After I graduate**
      I have not decided my job yet, but my current wanted job is Korea Housing Finance Corporation. 
      I just want to get my job in public enterprise. But I want to use what I learned from my University.

      Plan B is get a job which is abroad.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
